name: Deploy DAILY ALERT LIVE
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy_lambda:
    name: Deploy lambda function LIVE
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: zip Lambda Function
        run: |
          zip -r9 lambda.zip . -x test/\*
      - name: AWS Deploy LIVE
        run: |
          aws lambda update-function-code --function-name get_daily_alert --zip-file fileb://lambda.zip
